-- DROP TABLE AEROPUERTO
CREATE TABLE AEROPUERTO (
    AERO_ID SERIAL NOT NULL,
    NOMBRE CHARACTER VARYING(80) NOT NULL,
    IATA CHARACTER VARYING(5) NOT NULL,
    UBICACION CHARACTER VARYING(80) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE PK FOR TABLE AEROPUERTO
ALTER TABLE AEROPUERTO ADD CONSTRAINT AEROPUERTO_PK PRIMARY KEY (AERO_ID);

-- DROP TABLE AVION
CREATE TABLE AVION (
    AVIO_ID SERIAL NOT NULL,
    MODELO CHARACTER VARYING(30),
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE PK FOR TABLE AVION
ALTER TABLE AVION ADD CONSTRAINT AVION_PK PRIMARY KEY (AVIO_ID);

-- DROP TABLE VUELO
CREATE TABLE VUELO (
    VUEL_ID SERIAL NOT NULL,
    AERO_ID_ORIGEN INTEGER NOT NULL,
    AERO_ID_DESTINO INTEGER NOT NULL,
    PRECIO NUMERIC(19,2),
    HORA_SALIDA TIMESTAMP WITH TIME ZONE,
    HORA_LLEGADA TIMESTAMP WITH TIME ZONE,
    PRECIO_ASIENTO_VIP NUMERIC(19,2),
    PRECIO_ASIENTO_NORMAL NUMERIC(19,2),
    PRECIO_ASIENTO_BASICO NUMERIC(19,2),
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE INDEXES FOR TABLE VUELO
CREATE INDEX IX_VUEL_AERO_ORIGEN ON VUELO (AERO_ID_ORIGEN);
CREATE INDEX IX_VUEL_AERO_DESTINO ON VUELO (AERO_ID_DESTINO);
-- CREATE PK FOR TABLE VUELO
ALTER TABLE VUELO ADD CONSTRAINT VUELO_PK PRIMARY KEY (VUEL_ID);

-- DROP TABLE RESERVA
CREATE TABLE RESERVA (
    RESE_ID SERIAL NOT NULL,
    VUEL_ID INTEGER NOT NULL,
    ASIE_ID INTEGER NOT NULL,
    USUA_ID INTEGER NOT NULL,
    PRECIO_TOTAL NUMERIC(19,2),
    ESTADO_PAGO CHARACTER VARYING(1),
    FECHA TIMESTAMP WITH TIME ZONE NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE INDEXES FOR TABLE RESERVA
CREATE INDEX IX_RESE_VUEL ON RESERVA (VUEL_ID);
CREATE INDEX IX_RESE_ASIE ON RESERVA (ASIE_ID);
CREATE INDEX IX_RESE_USUA ON RESERVA (USUA_ID);
-- CREATE PK FOR TABLE RESERVA
ALTER TABLE RESERVA ADD CONSTRAINT RESERVA_PK PRIMARY KEY (RESE_ID);

-- DROP TABLE TIPO_ASIENTO
CREATE TABLE TIPO_ASIENTO (
    TIAS_ID SERIAL NOT NULL,
    DESCRIPCION CHARACTER VARYING(30) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE PK FOR TABLE TIPO_ASIENTO
ALTER TABLE TIPO_ASIENTO ADD CONSTRAINT TIPO_ASIENTO_PK PRIMARY KEY (TIAS_ID);

-- DROP TABLE ASIENTO
CREATE TABLE ASIENTO (
    ASIE_ID SERIAL NOT NULL,
    TIAS_ID INTEGER NOT NULL,
    AVIO_ID INTEGER NOT NULL,
    UBICACION CHARACTER VARYING(12),
    PRECIO NUMERIC(19,2),
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE INDEXES FOR TABLE ASIENTO
CREATE INDEX IX_ASIE_TIAS ON ASIENTO (TIAS_ID);
CREATE INDEX IX_ASIE_AVIO ON ASIENTO (AVIO_ID);
-- CREATE PK FOR TABLE ASIENTO
ALTER TABLE ASIENTO ADD CONSTRAINT ASIENTO_PK PRIMARY KEY (ASIE_ID);

-- DROP TABLE ROL_USUARIO
CREATE TABLE ROL_USUARIO (
    ROUS_ID SERIAL NOT NULL,
    DESCRIPCION CHARACTER VARYING(30) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE PK FOR TABLE ROL_USUARIO
ALTER TABLE ROL_USUARIO ADD CONSTRAINT ROL_USUARIO_PK PRIMARY KEY (ROUS_ID);

-- DROP TABLE USUARIO
CREATE TABLE USUARIO (
    USUA_ID SERIAL NOT NULL,
    ROUS_ID INTEGER,
    CEDULA CHARACTER VARYING(12) NOT NULL,
    NOMBRE CHARACTER VARYING(30) NOT NULL,
    APELLIDO CHARACTER VARYING(30) NOT NULL,
    CORREO CHARACTER VARYING(50) NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE INDEXES FOR TABLE USUARIO
CREATE INDEX IX_USUA_ROUS ON USUARIO (ROUS_ID);
-- CREATE PK FOR TABLE USUARIO
ALTER TABLE USUARIO ADD CONSTRAINT USUARIO_PK PRIMARY KEY (USUA_ID);

-- DROP TABLE FACTURA
CREATE TABLE FACTURA (
    FACT_ID SERIAL NOT NULL,
    RESE_ID INTEGER NOT NULL,
    FECHA TIMESTAMP WITH TIME ZONE NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE INDEXES FOR TABLE FACTURA
CREATE INDEX IX_FACT_RESE ON FACTURA (RESE_ID);
-- CREATE PK FOR TABLE FACTURA
ALTER TABLE FACTURA ADD CONSTRAINT FACTURA_PK PRIMARY KEY (FACT_ID);

-- DROP TABLE TRAYECTO
CREATE TABLE TRAYECTO (
    TRAY_ID SERIAL NOT NULL,
    AVIO_ID INTEGER NOT NULL,
    AERO_ID_ORIGEN INTEGER NOT NULL,
    AERO_ID_DESTINO INTEGER NOT NULL,
    HORA_SALIDA TIMESTAMP WITH TIME ZONE,
    HORA_LLEGADA TIMESTAMP WITH TIME ZONE,
    VUEL_ID INTEGER NOT NULL,
    ESTADO CHARACTER VARYING(1) NOT NULL DEFAULT 'A'
);
-- CREATE INDEXES FOR TABLE TRAYECTO
CREATE INDEX IX_TRAY_AERO_ORIGEN ON TRAYECTO (AERO_ID_ORIGEN);
CREATE INDEX IX_TRAY_AERO_DESTINO ON TRAYECTO (AERO_ID_DESTINO);
CREATE INDEX IX_TRAY_VUEL ON TRAYECTO (VUEL_ID);
CREATE INDEX IX_TRAY_AVIO ON TRAYECTO (AVIO_ID);


-- RELATIONSHIPS
ALTER TABLE RESERVA
    ADD CONSTRAINT RESE_VUEL_FK FOREIGN KEY ( VUEL_ID )
        REFERENCES VUELO ( VUEL_ID )
            ON DELETE CASCADE;

ALTER TABLE RESERVA
    ADD CONSTRAINT RESE_ASIE_FK FOREIGN KEY ( ASIE_ID )
        REFERENCES ASIENTO ( ASIE_ID )
            ON DELETE CASCADE;

ALTER TABLE RESERVA
    ADD CONSTRAINT RESE_USUA_FK FOREIGN KEY ( USUA_ID )
        REFERENCES USUARIO ( USUA_ID )
            ON DELETE CASCADE;

ALTER TABLE ASIENTO
    ADD CONSTRAINT ASIE_TIAS_FK FOREIGN KEY ( TIAS_ID )
        REFERENCES TIPO_ASIENTO ( TIAS_ID )
            ON DELETE CASCADE;

ALTER TABLE ASIENTO
    ADD CONSTRAINT ASIE_AVIO_FK FOREIGN KEY ( AVIO_ID )
        REFERENCES AVION ( AVIO_ID )
            ON DELETE CASCADE;

ALTER TABLE USUARIO
    ADD CONSTRAINT USUA_ROUS_FK FOREIGN KEY ( ROUS_ID )
        REFERENCES ROL_USUARIO ( ROUS_ID )
            ON DELETE CASCADE;

ALTER TABLE FACTURA
    ADD CONSTRAINT FACT_RESE_FK FOREIGN KEY ( RESE_ID )
        REFERENCES RESERVA ( RESE_ID )
            ON DELETE CASCADE;

ALTER TABLE TRAYECTO
    ADD CONSTRAINT TRAY_AERO_ORIGEN_FK FOREIGN KEY ( AERO_ID_ORIGEN )
        REFERENCES AEROPUERTO ( AERO_ID )
            ON DELETE CASCADE;

ALTER TABLE TRAYECTO
    ADD CONSTRAINT TRAY_AERO_DESTINO_FK FOREIGN KEY ( AERO_ID_DESTINO )
        REFERENCES AEROPUERTO ( AERO_ID )
            ON DELETE CASCADE;

ALTER TABLE TRAYECTO
    ADD CONSTRAINT TRAY_VUEL_FK FOREIGN KEY ( VUEL_ID )
        REFERENCES VUELO ( VUEL_ID )
            ON DELETE CASCADE;

ALTER TABLE TRAYECTO
    ADD CONSTRAINT TRAY_AVIO_FK FOREIGN KEY ( AVIO_ID )
        REFERENCES AVION ( AVIO_ID )
            ON DELETE CASCADE;

ALTER TABLE VUELO
    ADD CONSTRAINT VUEL_AERO_ORIGEN_FK FOREIGN KEY ( AERO_ID_ORIGEN )
        REFERENCES AEROPUERTO ( AERO_ID )
            ON DELETE CASCADE;

ALTER TABLE VUELO
    ADD CONSTRAINT VUEL_AERO_DESTINO_FK FOREIGN KEY ( AERO_ID_DESTINO )
        REFERENCES AEROPUERTO ( AERO_ID )
            ON DELETE CASCADE;
